# Site settings
title: rantings from a dark place
header-img: img/home-bg.png
email: tpms123@gmail.com
copyright_name: vtsowell
description: > # this means to ignore newlines until "baseurl:"
  my journey through coding and other life events
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vtsowell
learn_profile: vtsowell
email_username: tpms123@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
